import sqlite3


try:
    db=sqlite3.connect("ip.sqlite")

    #Criação das tabelas
    # db.execute("""
    # 	CREATE TABLE delay(description text(30), id integer)
    # 	""")
    # db.execute("""
    # 	CREATE TABLE throughput(description text(30), id integer)
    # 	""")
    # db.execute("""
    # 	CREATE TABLE reliability(description text(30), id integer)
    # 	""")
    # db.execute("""
    # 	CREATE TABLE monetary_cost(description text(30), id integer)
    # 	""")
    # db.execute("""
    # 	CREATE TABLE fragmentation(description text(30), id integer)
    # 	""")
    # db.execute("""
    # 	CREATE TABLE more_fragments(description text(30), id integer)
    # 	""")
    # db.execute("""
    # 	CREATE TABLE protocol(description text(30), id integer)
    # 	""")

    #Inserção de dado
    # db.execute("INSERT INTO precedence VALUES ('0 - Routine or Best Effort', 0)")
    # db.execute("INSERT INTO precedence VALUES ('1 - Priority', 1)")
    # db.execute("INSERT INTO precedence VALUES ('2 - Immediate', 2)")
    # db.execute("INSERT INTO precedence VALUES ('3 - Flash', 3)")
    # db.execute("INSERT INTO precedence VALUES ('4 - Flash Override', 4)")
    # db.execute("INSERT INTO precedence VALUES ('5 - Critical', 5)")
    # db.execute("INSERT INTO precedence VALUES ('6 - Internetwork Control', 6)")
    # db.execute("INSERT INTO precedence VALUES ('7 - Network Control', 7)")

    # db.execute("INSERT INTO delay VALUES ('0 - Normal delay', 0)")
    # db.execute("INSERT INTO delay VALUES ('1 - Low delay', 1)")

    # db.execute("INSERT INTO throughput VALUES ('0 - Normal throughput', 0)")
    # db.execute("INSERT INTO throughput VALUES ('1 - High throughput', 1)")

    # db.execute("INSERT INTO reliability VALUES ('0 - Normal reliability', 0)")
    # db.execute("INSERT INTO reliability VALUES ('1 - High reliability', 1)")

    # db.execute("INSERT INTO monetary_cost VALUES ('0 - Normal monetary cost', 0)")
    # db.execute("INSERT INTO monetary_cost VALUES ('1 - Minimize monetary cost', 1)")

    # db.execute("INSERT INTO fragmentation VALUES ('0 - Fragment if necessary', 0)")
    # db.execute("INSERT INTO fragmentation VALUES ('1 - Do not fragment', 1)")

    # db.execute("INSERT INTO more_fragments VALUES ('0 - This is the last fragment', 0)")
    # db.execute("INSERT INTO more_fragments VALUES ('1 - More fragments follow this fragment', 1)")

    # db.execute("INSERT INTO protocol VALUES ('0 - IPv6 Hop-by-Hop Option', 0)")
    # db.execute("INSERT INTO protocol VALUES ('1 - ICMP, Internet Control Message Protocol', 1)")
    # db.execute("INSERT INTO protocol VALUES ('2 - IGMP, Internet Group Management Protocol', 2)")
    # db.execute("INSERT INTO protocol VALUES ('3 - GGP, Gateway to Gateway Protocol', 3)")
    # db.execute("INSERT INTO protocol VALUES ('4 - IP in IP encapsulation', 4)")
    # db.execute("INSERT INTO protocol VALUES ('5 - ST, Internet Stream Protocol', 5)")
    # db.execute("INSERT INTO protocol VALUES ('6 - TCP, Transmission Control Protocol', 6)")
    # db.execute("INSERT INTO protocol VALUES ('7 - UCL, CBT', 7)")
    # db.execute("INSERT INTO protocol VALUES ('8 - EGP, Exterior Gateway Protocol', 8)")
    # db.execute("INSERT INTO protocol VALUES ('9 - IGRP', 9)")
    # db.execute("INSERT INTO protocol VALUES ('10 - BBN RCC Monitoring', 10)")
    # db.execute("INSERT INTO protocol VALUES ('11 - NVP, Network Voice Protocol', 11)")
    # db.execute("INSERT INTO protocol VALUES ('12 - PUP', 12)")
    # db.execute("INSERT INTO protocol VALUES ('13 - ARGUS',13)")
    # db.execute("INSERT INTO protocol VALUES ('14 - EMCON, Emission Control Protocol',14)")
    # db.execute("INSERT INTO protocol VALUES ('15 - XNET, Cross Net Debugger',15)")
    # db.execute("INSERT INTO protocol VALUES ('16 - Chaos',16)")
    # db.execute("INSERT INTO protocol VALUES ('17 - UDP, User Datagram Protocol',17)")
    # db.execute("INSERT INTO protocol VALUES ('18 - TMux, Transport Multiplexing Protocol',18)")
    # db.execute("INSERT INTO protocol VALUES ('19 - DCN Measurement Subsystems',19)")
    # db.execute("INSERT INTO protocol VALUES ('20 - HMP, Host Monitoring Protocol',20)")
    # db.execute("INSERT INTO protocol VALUES ('21 - Packet Radio Measurement',21)")
    # db.execute("INSERT INTO protocol VALUES ('22 - XEROX NS IDP',22)")
    # db.execute("INSERT INTO protocol VALUES ('23 - Trunk-1',23)")
    # db.execute("INSERT INTO protocol VALUES ('24 - Trunk-2',24)")
    # db.execute("INSERT INTO protocol VALUES ('25 - Leaf-1',25)")
    # db.execute("INSERT INTO protocol VALUES ('26 - Leaf-2',26)")
    # db.execute("INSERT INTO protocol VALUES ('27 - RDP, Reliable Data Protocol',27)")
    # db.execute("INSERT INTO protocol VALUES ('28 - IRTP, Internet Reliable Transaction Protocol',28)")
    # db.execute("INSERT INTO protocol VALUES ('29 - ISO Transport Protocol Class 4',29)")
    # db.execute("INSERT INTO protocol VALUES ('30 - NETBLT, Network Block Transfer',30)")
    # db.execute("INSERT INTO protocol VALUES ('31 - MFE Network Services Protocol',31)")
    # db.execute("INSERT INTO protocol VALUES ('32 - MERIT Internodal Protocol',32)")
    # db.execute("INSERT INTO protocol VALUES ('33 - Sequential Exchange Protocol',33)")
    # db.execute("INSERT INTO protocol VALUES ('34 - Third Party Connect Protocol',34)")
    # db.execute("INSERT INTO protocol VALUES ('35 - IDPR, Inter-Domain Policy Routing Protocol',35)")
    # db.execute("INSERT INTO protocol VALUES ('36 - XTP, Xpress Transfer Protocol',36)")
    # db.execute("INSERT INTO protocol VALUES ('37 - Datagram Delivery Protocol',37)")
    # db.execute("INSERT INTO protocol VALUES ('38 - IDPR, Control Message Transport Protocol',38)")
    # db.execute("INSERT INTO protocol VALUES ('39 - TP++ Transport Protocol',39)")
    # db.execute("INSERT INTO protocol VALUES ('40 - IL Transport Protocol',40)")
    # db.execute("INSERT INTO protocol VALUES ('41 - IPv6 over IPv4',41)")
    # db.execute("INSERT INTO protocol VALUES ('42 - SDRP, Source Demand Routing Protocol',42)")
    # db.execute("INSERT INTO protocol VALUES ('43 - IPv6 Routing header',43)")
    # db.execute("INSERT INTO protocol VALUES ('44 - IPv6 Fragment header',44)")
    # db.execute("INSERT INTO protocol VALUES ('45 - IDRP, Inter-Domain Routing Protocol',45)")
    # db.execute("INSERT INTO protocol VALUES ('46 - RSVP, Reservation Protocol',46)")
    # db.execute("INSERT INTO protocol VALUES ('47 - GRE, General Routing Encapsulation',47)")
    # db.execute("INSERT INTO protocol VALUES ('48 - MHRP, Mobile Host Routing Protocol',48)")
    # db.execute("INSERT INTO protocol VALUES ('49 - BNA',49)")
    # db.execute("INSERT INTO protocol VALUES ('50 - ESP, Encapsulating Security Payload',50)")
    # db.execute("INSERT INTO protocol VALUES ('51 - AH, Authentication Header',51)")
    # db.execute("INSERT INTO protocol VALUES ('52 - Integrated Net Layer Security TUBA',52)")
    # db.execute("INSERT INTO protocol VALUES ('53 - IP with Encryption',53)")
    # db.execute("INSERT INTO protocol VALUES ('54 - NARP, NBMA Address Resolution Protocol',54)")
    # db.execute("INSERT INTO protocol VALUES ('55 - Minimal Encapsulation Protocol',55)")
    # db.execute("INSERT INTO protocol VALUES ('56 - TLSP, Transport Layer Security Protocol',56)")
    # db.execute("INSERT INTO protocol VALUES ('57 - SKIP',57)")
    # db.execute("INSERT INTO protocol VALUES ('58 - ICMPv6, Internet Control Message Protocol for IPv6',58)")
    # db.execute("INSERT INTO protocol VALUES ('59 - IPv6 No Next Header',59)")
    # db.execute("INSERT INTO protocol VALUES ('60 - Destination Options for IPv6',60)")
    # db.execute("INSERT INTO protocol VALUES ('61 - Any host internal protocol',61)")
    # db.execute("INSERT INTO protocol VALUES ('62 - CFTP',62)")
    # db.execute("INSERT INTO protocol VALUES ('63 - Any local network',63)")
    # db.execute("INSERT INTO protocol VALUES ('64 - SATNET and Backroom EXPAK',64)")
    # db.execute("INSERT INTO protocol VALUES ('65 - Kryptolan',65)")
    # db.execute("INSERT INTO protocol VALUES ('66 - MIT Remote Virtual Disk Protocol',66)")
    # db.execute("INSERT INTO protocol VALUES ('67 - Internet Pluribus Packet Core',67)")
    # db.execute("INSERT INTO protocol VALUES ('68 - Any distributed file system',68)")
    # db.execute("INSERT INTO protocol VALUES ('69 - SATNET Monitoring',69)")
    # db.execute("INSERT INTO protocol VALUES ('70 - VISA Protocol',70)")
    # db.execute("INSERT INTO protocol VALUES ('71 - Internet Packet Core Utility',71)")
    # db.execute("INSERT INTO protocol VALUES ('72 - Computer Protocol Network Executive',72)")
    # db.execute("INSERT INTO protocol VALUES ('73 - Computer Protocol Heart Beat',73)")
    # db.execute("INSERT INTO protocol VALUES ('74 - Wang Span Network',74)")
    # db.execute("INSERT INTO protocol VALUES ('75 - Packet Video Protocol',75)")
    # db.execute("INSERT INTO protocol VALUES ('76 - Backroom SATNET Monitoring',76)")
    # db.execute("INSERT INTO protocol VALUES ('77 - SUN ND PROTOCOL-Temporary',77)")
    # db.execute("INSERT INTO protocol VALUES ('78 - WIDEBAND Monitoring',78)")
    # db.execute("INSERT INTO protocol VALUES ('79 - WIDEBAND EXPAK',79)")
    # db.execute("INSERT INTO protocol VALUES ('80 - ISO Internet Protocol',80)")
    # db.execute("INSERT INTO protocol VALUES ('81 - VMTP, Versatile Message Transaction Protocol',81)")
    # db.execute("INSERT INTO protocol VALUES ('82 - SECURE-VMTP',82)")
    # db.execute("INSERT INTO protocol VALUES ('83 - VINES',83)")
    # db.execute("INSERT INTO protocol VALUES ('84 - TTP',84)")
    # db.execute("INSERT INTO protocol VALUES ('85 - NSFNET-IGP',85)")
    # db.execute("INSERT INTO protocol VALUES ('86 - Dissimilar Gateway Protocol',86)")
    # db.execute("INSERT INTO protocol VALUES ('87 - TCF',87)")
    # db.execute("INSERT INTO protocol VALUES ('88 - EIGRP',88)")
    # db.execute("INSERT INTO protocol VALUES ('89 - OSPF / MOSPF',89)")
    # db.execute("INSERT INTO protocol VALUES ('90 - Sprite RPC Protocol',90)")
    # db.execute("INSERT INTO protocol VALUES ('91 - Locus Address Resolution Protocol',91)")
    # db.execute("INSERT INTO protocol VALUES ('92 - MTP, Multicast Transport Protocol',92)")
    # db.execute("INSERT INTO protocol VALUES ('93 - AX.25',93)")
    # db.execute("INSERT INTO protocol VALUES ('94 - IP-within-IP Encapsulation Protocol',94)")
    # db.execute("INSERT INTO protocol VALUES ('95 - Mobile Internetworking Control Protocol',95)")
    # db.execute("INSERT INTO protocol VALUES ('96 - Semaphore Communications Sec. Pro',96)")
    # db.execute("INSERT INTO protocol VALUES ('97 - Ethernet-within-IP Encapsulation',97)")
    # db.execute("INSERT INTO protocol VALUES ('98 - Encapsulation Header',98)")
    # db.execute("INSERT INTO protocol VALUES ('99 - Any private encryption scheme',99)")
    # db.execute("INSERT INTO protocol VALUES ('100 - GMTP',100)")

    teste = db.execute("SELECT * FROM protocol WHERE id==6")
    print(teste.fetchone())
    db.commit()
    db.close()
except:	
    print("[-] Error: ip.sqlite database not found")
